### ISSUE TITLE
Add support for migration of content entries 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [kneeclass/Contentful-environment-soft-migration#1]
Might be an odd request. But I’d really love to see an additional feature allowing ,s to migrate content entries to and from environments. 

Here’s the scenario. Lets say I’m working on a feature for several weeks. While I’m using this to sync model changes - it would be super handy to be able to migrate actual content entries to lower environments while working on a long running feature. Pretty much syncing master content downstream while a feature is going worked on for possibly weeks

**Comment by ScriptedAlchemy** [comment]
@kneeclass any interest in supporting this?

**Comment by kneeclass** [comment]
Hi
It would be a nice feature but this project is aimed at only handling content models and UI Extensions.

If i have time in the future i might create another CLI based on actual Content.

Best regards Niklas

**Comment by ScriptedAlchemy** [comment]
Would be keen to lend a hand if you spin something up
